### PR TITLE
Image resizer now cleans view after resize is committed/cancelled

### LINKED ISSUE #6060: Image resizer should clean the view after itself
## 📝 Provide detailed reproduction steps (if any)

At the moment, `Resizer` makes changes directly in the view. This is not recommended usually but in this case, it makes sense (we don't want to so many changes done on model).

What I don't like is that the `Resizer` does not clean after itself. When the drag ends and the `commit` method is fired and `onCommit` callback is executed, it should clean the changes (re-set width to the value it was before resizing).

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Image resize now cleans up temporary view `width` style changes. Closes ckeditor/ckeditor5#6060.

---

### Additional information

Reverting should be handled in `_cleanup` method as it guarantees it to happen whether resize process was committed or cancelled.

### CODE REVIEW

File: tests/widgetresize.js [hunk 1]
```diff
@@ -377,6 +378,19 @@ describe( 'WidgetResize', () => {
...
+			// Note that ultimately width should be changed, but through a model converter, not with direct view changes (#6060).
+			createResizer();
+
+			const usedHandle = 'bottom-right';
+			const domParts = getWidgetDomParts( editor, widget, usedHandle );
+			const finalPointerPosition = getHandleCenterPoint( domParts.widget, usedHandle ).moveBy( 40, 40 );
+
+			resizerMouseSimulator.dragTo( editor, domParts.resizeHandle, finalPointerPosition );
+
+			expect( widget.getStyle( 'width' ) ).to.be.equal( '25%' );
```
Comment (oleq) [inline tests/widgetresize.js:391]:
```suggestion
			expect( widget.getStyle( 'width' ) ).to.equal( INITIAL_WIDGET_WIDTH );
```

File: src/widgetresize/resizer.js [hunk 2]
```diff
@@ -269,6 +277,12 @@ export default class Resizer {
 	_cleanup() {
 		this._sizeUI.dismiss();
 		this._sizeUI.isVisible = false;
+
+		const editingView = this._options.editor.editing.view;
+
+		editingView.change( writer => {
```
Comment (jodator) [inline src/widgetresize/resizer.js:283]: I wonder if this is the reason of:



Found on Firefox but also visible on Chrome: after ending resizing the image border of the original size flickers. It happens on every drag (not GIF drops some frames and is not always visible).

What I can thinkof is a single commit block (if doable).

**Review by jodator — COMMENTED** [review]
I've found one UX issue - it flickers (dunno if related to this issue).

File: src/widgetresize/resizer.js (hunk 2 above)
Comment (oleq) [reply src/widgetresize/resizer.js:283]: Yeah, this is probably because things are done in two batches and the browser gets a chance to re-pain in between. I don't know how to address this unless I spend some serious time digging into the code.

Comment (mlewand) [reply src/widgetresize/resizer.js:286]: Doh :facepalm: @jodator is right. I was a little overconfident with the change and did it only by writing unit test and making a fix. Without realizing there might be some rendering artifacts :smiley:

**Comment by mlewand** [comment]
@ckeditor/qa-team Guys can I ask you to double check this little change whether there are no visible regressions vs `master`?

**Comment by mlewand** [comment]
Tests are passing locally for me, 100% CC. Don't know what's up with the CI.

**Comment by jodator** [comment]
@mlewand I can confirm that the test don't work :stuck\_out\_tongue\_winking\_eye:. Merged with master to fix ;)

Could you also add a test to ensure that this change is executed in one `view.change()` block? Dunno if we have events for that as we can test for similar thing in the model.

**Comment by FilipTokarski** [comment]
Tested in all browsers, looks good.

**Comment by mlewand** [comment]
> @mlewand I can confirm that the test don't work 😜. Merged with master to fix ;)

Seems somebody had outdated `master`s on other repos 🤔

@jodator TBH I'd rather skip on making this test - there's gonna be a major effort to make this TC while this issue was meant to be a quick one.

**Comment by Reinmar** [comment]
> @jodator TBH I'd rather skip on making this test - there's gonna be a major effort to make this TC while this issue was meant to be a quick one.

This is a pretty simple test to write, AFAICT. You just need to listen to the `View#render` event and check if it was fired once.

As far as I can see, this PR actually had this bug initially, so we should definitely have a test for this scenario. If the mistake could have been done once it can easily be repeated.

**Comment by mlewand** [comment]
Added the test, I referenced the proper comment to give at least some clarity for a person that faces it in the future.

**Comment by Reinmar** [comment]
I think that this should be a separate test as we're testing for the number of renders. Also, why 3? That's an odd number.

I'll fix these issues.

**Comment by Reinmar** [comment]
BTW, when I started digging into this, it turned out that this render count check passes before the issue that it was supposed to cover was fixed. When adding a test, you should verify that it's failing without the thing that you test (like in TDD, but to me it can also be done afterwards).

**Comment by Reinmar** [comment]
I forgot to push the fixed test before merging this PR :facepalm:. I pushed it to master: edd37d8
