### PR TITLE
Use proper method to map a view to a DOM element in getBalloonPositio…

### LINKED ISSUE #87: Adding toolbar to widget fails
I'm attempting to add a toolbar to my formula widget with this code in my plugin class:

```
afterInit() {
        const editor = this.editor;
        const widgetToolbarRepository = editor.plugins.get( WidgetToolbarRepository );

        widgetToolbarRepository.register( 'formula', {
            items: editor.config.get( 'formula.items' ),
            getRelatedElement: () => {
                let selectedElement = editor.model.document.selection.getSelectedElement();
                return selectedElement && selectedElement.name === 'formula' ? selectedElement : null;
            }
        } );
 }
```

I see the getRelatedElement function getting called and successfully returning an element when my formula widget is selected.

However, I get the following stack trace:
`domconverter.js:254 Uncaught TypeError: Cannot read property 'createElement' of undefined
    at DomConverter.viewToDom (domconverter.js:254)
    at getBalloonPositionData (widgettoolbarrepository.js:333)
    at WidgetToolbarRepository._showToolbar (widgettoolbarrepository.js:283)
    at WidgetToolbarRepository._updateToolbarsVisibility (widgettoolbarrepository.js:244)
    at ClassicEditorUI.<anonymous> (widgettoolbarrepository.js:109)
    at ClassicEditorUI.fire (emittermixin.js:242)
    at ClassicEditorUI.update (editorui.js:103)
    at Document.<anonymous> (editorui.js:73)
    at Document.fire (emittermixin.js:242)
    at View.<anonymous> (view.js:201)`

I've traced the issue to line 246 of ckeditor5-widget/src/widgettoolbarrepository.js

`target: editingView.domConverter.viewToDom( relatedElement )`

This function call only passes in one parameter, but viewToDom expects two: 

`viewToDom(viewNode, domDocument) `

When viewToDom later calls:

`domElement = domDocument.createElement(viewNode.name);`

It throws the error "Cannot read property 'createElement' of undefined"

And no toolbar appears.

### PR DESCRIPTION
**Pull request by jodator**
Use proper method to map a view to a DOM element in getBalloonPositionData().

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Use proper method to map a view to a DOM element when getting balloon position data. Closes #87.

---

### Additional information

* I don't see a need for adding tests as this is more a typo then a bug but feel free to R- this :)

### CODE REVIEW

File: src/widgettoolbarrepository.js [hunk 1]
```diff
@@ -243,7 +243,7 @@ function getBalloonPositionData( editor, relatedElement ) {
 	const defaultPositions = BalloonPanelView.defaultPositions;
 
 	return {
-		target: editingView.domConverter.viewToDom( relatedElement ),
+		target: editingView.domConverter.mapViewToDom( relatedElement ),
```
Comment (oleq) [inline src/widgettoolbarrepository.js]: We need a test for this change.

Comment (jodator) [reply src/widgettoolbarrepository.js]: I'm trying to write a test for this. And the only case when this fails if the `getRelatedElement()` will return an object with API similar to view element and the `viewToDom` will try to create a DOM node and somehow the domDocument is null. I'm lost how to write a test for this.

Also, this issue is really about the wrong method use with wrong parameters. Also changing `viewToDom` to proper `mapViewToDom` does not fix the issue with wrong API use.
